package main;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.Timer;

public class Clock extends javax.swing.JPanel {
    
    private final SimpleDateFormat TIME_FORMATTER = new SimpleDateFormat("hh:mm:ss a");
    private final SimpleDateFormat DAY_FORMATTER = new SimpleDateFormat("EEEE");
    private final SimpleDateFormat DATE_FORMATTER = new SimpleDateFormat("MMMM d, yyyy");
    private final Timer TIMER;
    
    public Clock() {
        initComponents();
        TIMER = new Timer(1000, e -> {
            time.setText(TIME_FORMATTER.format(Calendar.getInstance().getTime())); 
            date.setText(DATE_FORMATTER.format(Calendar.getInstance().getTime()));
            day.setText(DAY_FORMATTER.format(Calendar.getInstance().getTime()));
        });
        TIMER.setInitialDelay(0);
        TIMER.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        time = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        day = new javax.swing.JLabel();

        setBackground(new java.awt.Color(39, 39, 39));

        time.setFont(new java.awt.Font("Bookman Old Style", 0, 48)); // NOI18N
        time.setForeground(new java.awt.Color(153, 153, 153));
        time.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        time.setText("00:00:00");

        date.setFont(new java.awt.Font("Bookman Old Style", 0, 36)); // NOI18N
        date.setForeground(new java.awt.Color(153, 153, 153));
        date.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        day.setFont(new java.awt.Font("Bookman Old Style", 0, 36)); // NOI18N
        day.setForeground(new java.awt.Color(153, 153, 153));
        day.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(time, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(day, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                .addGap(73, 73, 73))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(day, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel date;
    private javax.swing.JLabel day;
    private javax.swing.JLabel time;
    // End of variables declaration//GEN-END:variables
}
